# CDS 230 - Modeling and Simulation 1 - Fall 2019

# Example Uncertain Games

**Lecturer:** Dr. Hamdi Kavak

**Email:** hkavak@gmu.edu

**Lecture:** 11/11/2019

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## 1. Yahtzee example

In [2]:
# five random integers to represent 5 dice
dice = np.random.randint(1,7,size=5)
print(dice)

[2 2 3 6 2]


In [3]:
# we will keep track of how many occurances we see for each possible values in dice (1,2,3,4,5,6)
# initially, all are set to zero
counts = np.zeros(6)

In [4]:
# array element with index 0 represents the count for dice value 1
# array element with index 1 represents the count for dice value 2
# ...
# array element with index 5 represents the count for dice value 6
counts

array([0., 0., 0., 0., 0., 0.])

In [5]:
# we loop through five dice and increase the corresponding count values.
# recall that counts array indexes start from 0 while dice values start from 1. that's why you see "die-1" for the index
for die in dice:
    counts[die-1] += 1

In [6]:
# the state of the counts after one roll is counted
counts

array([0., 3., 1., 0., 0., 1.])

In [7]:
# this gives the most repeating dice value among 5 dices
counts.max()

3.0

In [8]:
# this gives the value of the most repeating dice value. We added +1 because of the disparity between count index and dice value
counts.argmax() + 1

2

In [9]:
# let's keep these two values in a variable
number_of_dice_kept = counts.max()
value_we_keep = counts.argmax() + 1

In [10]:
# roll again

In [11]:
if number_of_dice_kept == 1: # this means all value in 5 dice were unique so we will have to roll all dice again
    number_of_dice_kept=0 # we assign this to 0 so that we still generate 5 random numbers
dice2 = np.random.randint(1,7,size=5-int(number_of_dice_kept))
print(dice2)

[3 5]


In [12]:
# we have to do same checks again. Let's implement a more compact version

## Compact version

In [13]:
# the following two variables will keep track of our Yahtzee state
number_of_dice_kept = 0
value_we_keep = 0

for i in range(3): # we try up to three times.
    # roll five dice (in the first roll) and potentially <5 dice roll
    dice = np.random.randint(1,7,size=5-number_of_dice_kept)
    print(dice)
    
    # if we selected a value previously to make the Yahtzee combination, 
    # we just count how many matches between the selected value and new roll
    if value_we_keep > 0:
        for die in dice:
            if die == value_we_keep:
                number_of_dice_kept = number_of_dice_kept + 1
    else:
        # we will keep track of how many occurances we see for each possible values in dice (1,2,3,4,5,6)
        # initially, all are set to zero
        counts = np.zeros(6)

        # we loop through five dice and increase the corresponding count values.
        # recall that counts array indexes start from 0 while dice values start from 1. that's why you see "die-1" for the index
        for die in dice:
            counts[die-1] += 1

        number_of_dice_kept = int(counts.max())
        if number_of_dice_kept == 1: # meaning all dice show a different value, we roll all five again
            value_we_keep = 0
            number_of_dice_kept = 0
        else:
            value_we_keep = counts.argmax() + 1

print("We got",number_of_dice_kept, "dice with value", value_we_keep)    

[4 4 5 6 5]
[3 6 3]
[3 1 1]
We got  2 dice with value 4


In [14]:
# numpy test
test_array = np.array([0, 2, 2, 0, 0, 0])
print(test_array.max())
print(test_array.argmax())

2
1


## 2. Card game example