# CDS 230 - Modeling and Simulation 1 - Fall 2019

# Monte Carlo Simulation

**Lecturer:** Dr. Hamdi Kavak

**Email:** hkavak@gmu.edu

**Lecture:** 11/13/2019

### Coin flipping example

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# two possible values
# 0: Heads
# 1: Tails
np.random.choice([0,1])

0

In [3]:
# five coin flips
np.random.choice([0,1],size=5)

array([0, 1, 1, 1, 0])

In [4]:
# 10 runs
observations = np.random.choice([0,1],size=10)

In [5]:
observations

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 1])

In [6]:
odds_tails = 100 * observations.sum() / len(observations)  # number of times we observed 1's / total tosses
odds_heads = 100 - odds_tails
print(odds_tails)
print(odds_heads)

50.0
50.0


In [7]:
runs = [1, 10, 100, 1000, 10000]
for run in runs:
    observations = np.random.choice([0,1],size=run)
    odds_tails = 100 * observations.sum() / len(observations)  # number of times we observed 1's / total tosses
    odds_heads = 100 - odds_tails
    print("After ",run, " runs - odds of seeing heads is ", odds_heads)

After  1  runs - odds of seeing heads is  0.0
After  10  runs - odds of seeing heads is  70.0
After  100  runs - odds of seeing heads is  55.0
After  1000  runs - odds of seeing heads is  52.1
After  10000  runs - odds of seeing heads is  49.34


### Coin flipping example with sequential combinations

In [8]:
one_sequence = np.random.choice([0,1],size=3)
print(one_sequence)

[1 0 1]


### Slow running code

In [9]:
counter = 0
num_of_runs = 10
for i in range(num_of_runs):
    one_sequence = np.random.choice([0,1],size=3)
    if one_sequence.sum() == 0:
        counter = counter + 1
p=counter/num_of_runs
print("Number of runs:", num_of_runs, " - P(Heads,Heads,Heads)", p)
    

Number of runs: 10  - P(Heads,Heads,Heads) 0.3


In [10]:
# copy/pasted from above - slow version
counter = 0
num_of_runs = 1000000
for i in range(num_of_runs):
    one_sequence = np.random.choice([0,1],size=3)
    if one_sequence.sum() == 0:
        counter = counter + 1
p=counter/num_of_runs
print("Number of runs:", num_of_runs, " - P(Heads,Heads,Heads)", p)

Number of runs: 1000000  - P(Heads,Heads,Heads) 0.124833


In [11]:
all_runs = np.random.randint(0,2,size=(10,3))

In [12]:
print(all_runs)

[[0 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 1]
 [0 0 1]
 [1 0 1]
 [0 0 0]
 [0 0 1]
 [1 1 1]
 [1 1 0]]


In [13]:
counts = all_runs.sum(1)

In [14]:
zero_counts = counts==0

In [15]:
zero_counts.sum()

2

In [16]:
p = zero_counts.sum() / 10
print(p)

0.2


### Faster running code

In [17]:
# faster version
num_of_runs = 100000000

entire_runs = np.random.choice([0,1],size=(num_of_runs,3))
entire_runs_count = entire_runs.sum(1)
count_of_HHH = (entire_runs_count == 0).sum()
p=count_of_HHH/num_of_runs
print("Number of runs:", num_of_runs, " - P(Heads,Heads,Heads)", p)
    

Number of runs: 100000000  - P(Heads,Heads,Heads) 0.12501817


## Pi example

In [18]:
r = 1
# first location randomly set
x = np.random.uniform(-r,r)
y = np.random.uniform(-r,r)
print(x,y)

0.681731184513219 0.02858278515911561


In [19]:
import math
# if the distance to the center is lower than radius, it means the dart is within the circle
length = math.sqrt(x ** 2 + y ** 2)

In [20]:
print(length)

0.6823301133214398


In [21]:
# many runs....
runs = [10, 100, 1000, 10000, 100000]

for run in runs:
    count = 0
    
    for i in range(run):
        x = np.random.uniform(-r,r)
        y = np.random.uniform(-r,r)
        length = math.sqrt(x ** 2 + y ** 2)
        if length < r:
            count = count + 1
    
    p =  count / run
    # divided it by 4 to estimate the pi number
    pi =  p * 4
    #print("Ratio of darts inside circle:", p)
    print("Estimated pi value for ",run, " runs: ", pi)

Estimated pi value for  10  runs:  3.2
Estimated pi value for  100  runs:  3.28
Estimated pi value for  1000  runs:  3.168
Estimated pi value for  10000  runs:  3.1528
Estimated pi value for  100000  runs:  3.1338
