# CDS 230 - Modeling and Simulation 1 - Fall 2019
# Numpy

**Lecturer:** Dr. Hamdi Kavak

**Email:** hkavak@gmu.edu

**Lecture:** 10/7/2019


## 1. Importing numpy

In [2]:
import numpy as np

## 2. Creating arrays

In [3]:
vec = np.zeros( 5 )
vec

array([0., 0., 0., 0., 0.])

In [4]:
vec = np.full(5, 1.0)
vec

array([1., 1., 1., 1., 1.])

In [5]:
np.array([4,4,1,6])

array([4, 4, 1, 6])

In [6]:
np.array([4,4,1,6.0])

array([4., 4., 1., 6.])

In [7]:
np.array([4,4,1,"6"])

array(['4', '4', '1', '6'], dtype='<U21')

## 3. Creating arrays w/ random values

In [8]:
vec = np.random.random(4)
vec

array([0.75501967, 0.0262822 , 0.07794013, 0.89892791])

In [13]:
vec = np.random.randint(1,6,4)
vec

array([3, 3, 4, 1])

In [9]:
vec = np.random.random(100)
vec

array([0.35846469, 0.77451298, 0.15087849, 0.82660523, 0.17576449,
       0.71226487, 0.17593594, 0.39902983, 0.23795018, 0.92141048,
       0.0117508 , 0.91708938, 0.54539842, 0.74121229, 0.71757155,
       0.16266148, 0.26903274, 0.76150291, 0.94069854, 0.12357852,
       0.18019493, 0.6819162 , 0.91685318, 0.79641327, 0.98860359,
       0.57408123, 0.94118066, 0.93568715, 0.7397282 , 0.64016067,
       0.91817016, 0.78376564, 0.59234063, 0.13711589, 0.65232768,
       0.18254546, 0.5227466 , 0.17327965, 0.59023643, 0.80916433,
       0.81127616, 0.44741294, 0.39846879, 0.3209138 , 0.24765607,
       0.1818303 , 0.7226836 , 0.45560892, 0.69149294, 0.59434258,
       0.98837328, 0.9480647 , 0.96933242, 0.63722027, 0.38460225,
       0.93370954, 0.02181841, 0.52460362, 0.33157321, 0.43547651,
       0.18468617, 0.01223185, 0.16440112, 0.61954091, 0.93681645,
       0.19508115, 0.97413405, 0.81792091, 0.06204738, 0.65529382,
       0.36807633, 0.17149767, 0.85520454, 0.11964864, 0.97031

## 4. Slicing arrays

In [10]:
vec[0]

0.35846469065173314

In [11]:
vec[:4]

array([0.35846469, 0.77451298, 0.15087849, 0.82660523])

In [12]:
vec[-1]

0.36438616175314675

## 5. Matrix

In [14]:
mat = np.zeros((2,3))
mat

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
mat = np.random.random((2,3))
mat

array([[0.17706446, 0.53955867, 0.91566675],
       [0.59464253, 0.08648464, 0.80242614]])

## 6. Control printing

In [16]:
np.set_printoptions(precision=3)
mat

array([[0.177, 0.54 , 0.916],
       [0.595, 0.086, 0.802]])

## 7. Slicing matrices

In [17]:
mat[0,0]

0.17706445610094457

In [18]:
mat[0]

array([0.177, 0.54 , 0.916])

In [19]:
mat[:,0]

array([0.177, 0.595])

In [21]:
mat2 = np.random.random((10,10))
mat2

array([[0.865, 0.601, 0.326, 0.213, 0.635, 0.811, 0.328, 0.92 , 0.667,
        0.663],
       [0.865, 0.559, 0.66 , 0.07 , 0.375, 0.595, 0.714, 0.952, 0.55 ,
        0.762],
       [0.048, 0.241, 0.006, 0.048, 0.824, 0.453, 0.832, 0.726, 0.766,
        0.871],
       [0.873, 0.507, 0.097, 0.3  , 0.287, 0.836, 0.104, 0.889, 0.202,
        0.059],
       [0.48 , 0.151, 0.55 , 0.424, 0.842, 0.125, 0.021, 0.485, 0.521,
        0.429],
       [0.696, 0.147, 0.634, 0.355, 0.255, 0.108, 0.111, 0.092, 0.119,
        0.071],
       [0.968, 0.573, 0.391, 0.146, 0.749, 0.919, 0.621, 0.118, 0.581,
        0.98 ],
       [0.174, 0.812, 0.155, 0.382, 0.179, 0.668, 0.466, 0.937, 0.002,
        0.306],
       [0.843, 0.751, 0.769, 0.945, 0.313, 0.798, 0.925, 0.339, 0.899,
        0.082],
       [0.049, 0.416, 0.794, 0.908, 0.961, 0.821, 0.333, 0.816, 0.927,
        0.017]])

In [22]:
mat2[1:4]

array([[0.865, 0.559, 0.66 , 0.07 , 0.375, 0.595, 0.714, 0.952, 0.55 ,
        0.762],
       [0.048, 0.241, 0.006, 0.048, 0.824, 0.453, 0.832, 0.726, 0.766,
        0.871],
       [0.873, 0.507, 0.097, 0.3  , 0.287, 0.836, 0.104, 0.889, 0.202,
        0.059]])

In [23]:
mat2[1:4,2:4]

array([[0.66 , 0.07 ],
       [0.006, 0.048],
       [0.097, 0.3  ]])

In [24]:
v = [3,4,2]
h = [1,0,5]

mat2[v,h]

array([0.507, 0.48 , 0.453])

## 8. Setting values

In [26]:
mat3 = np.zeros((4,5))
print("Print before setting values")
print(mat3)
mat3[1:3, 2:5] = ((1,2,3), (4,5,6))
print("Print after setting values")
print(mat3)

Print before setting values
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Print after setting values
[[0. 0. 0. 0. 0.]
 [0. 0. 1. 2. 3.]
 [0. 0. 4. 5. 6.]
 [0. 0. 0. 0. 0.]]


## 9. Comparison

In [27]:
vec = np.random.random(4)
vec

array([0.153, 0.49 , 0.058, 0.347])

In [28]:
vec > 0.3

array([False,  True, False,  True])

In [29]:
np.where(vec > 0.3)[0]

array([1, 3])

## 10. Generating many random values

In [6]:
for i in range(200):
    print(np.random.randint(0,6,1), end=",")

[0],[0],[2],[4],[1],[0],[4],[0],[3],[0],[2],[5],[1],[1],[3],[1],[4],[5],[2],[3],[4],[2],[5],[1],[0],[4],[3],[5],[4],[3],[3],[5],[3],[3],[3],[5],[5],[1],[0],[1],[4],[1],[5],[2],[5],[3],[0],[5],[3],[5],[4],[2],[5],[0],[0],[3],[0],[2],[4],[0],[0],[0],[3],[4],[4],[4],[3],[5],[4],[4],[5],[2],[5],[2],[3],[1],[1],[0],[4],[5],[5],[1],[3],[5],[0],[4],[5],[4],[2],[1],[2],[1],[5],[2],[2],[3],[3],[5],[5],[4],[1],[5],[5],[5],[5],[3],[5],[5],[5],[1],[3],[3],[1],[3],[0],[4],[1],[3],[0],[0],[2],[0],[0],[0],[1],[2],[5],[5],[3],[2],[0],[1],[4],[5],[4],[3],[5],[3],[5],[0],[5],[0],[4],[4],[4],[5],[3],[5],[2],[3],[5],[3],[5],[0],[4],[3],[0],[5],[0],[0],[4],[0],[3],[1],[2],[1],[0],[5],[4],[3],[3],[3],[2],[2],[3],[3],[0],[4],[3],[2],[2],[1],[2],[2],[0],[4],[0],[3],[4],[0],[1],[3],[5],[3],[4],[4],[1],[1],[0],[2],

In [7]:
np.random.randint(0,6,200)

array([5, 1, 5, 1, 4, 1, 3, 4, 3, 5, 5, 2, 5, 0, 0, 2, 4, 3, 3, 4, 5, 1,
       5, 0, 0, 3, 2, 4, 3, 3, 0, 3, 5, 2, 5, 5, 3, 5, 3, 5, 2, 4, 3, 5,
       5, 2, 4, 3, 2, 5, 5, 5, 0, 2, 1, 2, 3, 1, 4, 0, 0, 3, 4, 2, 0, 4,
       0, 5, 1, 1, 0, 3, 4, 0, 3, 2, 5, 0, 0, 3, 3, 1, 4, 2, 4, 4, 0, 0,
       4, 5, 5, 4, 4, 4, 4, 3, 2, 2, 2, 4, 2, 3, 5, 3, 5, 1, 0, 2, 2, 2,
       0, 2, 5, 2, 5, 5, 2, 5, 0, 0, 2, 4, 2, 5, 4, 4, 4, 2, 1, 1, 2, 4,
       2, 5, 4, 2, 1, 0, 0, 2, 0, 5, 4, 1, 0, 3, 5, 1, 2, 4, 2, 0, 4, 0,
       2, 4, 2, 2, 4, 4, 1, 5, 4, 2, 3, 1, 1, 1, 5, 4, 3, 3, 0, 0, 1, 0,
       0, 2, 4, 5, 3, 5, 5, 3, 1, 5, 1, 3, 4, 2, 4, 0, 5, 4, 3, 5, 0, 1,
       0, 0])

In [8]:
np.random.randint(1,7,2)

array([2, 4])