# CDS 230 - Modeling and Simulation 1 - Fall 2019
# Dealing with Uncertainty

**Lecturer:** Dr. Hamdi Kavak

**Email:** hkavak@gmu.edu

**Lecture:** 11/04/2019

In [1]:
import random
import numpy as np
import matplotlib.pyplot as plt

## 1. Random numbers

### 1.1. Default random number generation [0,1)

In [2]:
random.random() # built-in python random number generator

0.06307777120650893

In [3]:
np.random.random() # numpy random number generator (preffered)

0.3906705873305315

In [4]:
np.random.random(5) # 5 values to be generated

array([0.65348309, 0.27415441, 0.01372371, 0.71346053, 0.54695058])

In [5]:
np.random.random((2,3))

array([[0.61078621, 0.07792854, 0.11373331],
       [0.04665458, 0.92737203, 0.3861151 ]])

### 1.2. Random Integer Generation

In [6]:
np.random.randint(5) # generates a number between 0 (inc) and 5 (exl)

3

In [7]:
np.random.randint(10,20) # generate a number between 10 and 20

14

In [8]:
np.random.randint(5,size=10)

array([3, 4, 0, 0, 3, 1, 4, 3, 1, 1])

In [9]:
np.random.randint(10,20,size=10)

array([10, 15, 16, 10, 10, 13, 15, 12, 19, 15])

In [10]:
np.random.randint(0,5,size=(3,4))

array([[4, 4, 0, 2],
       [1, 3, 4, 4],
       [0, 0, 4, 4]])

### 1.3. The concept of equal chances

In [11]:
np.random.uniform(0.,1.) # equal to np.random.random()

0.4921918549158054

In [12]:
np.random.uniform(-500.0, 500.0) # a random float between -500 and +500

389.21373647640064

In [13]:
np.random.uniform(0.0, 10.0, size=100) # 100 random floats between 0 and 10

array([7.73123491, 7.72278679, 7.84984113, 3.64597633, 3.09166542,
       2.1372517 , 4.56584416, 4.55322728, 1.49055408, 7.80140388,
       8.32915531, 6.80373627, 2.62093904, 3.28699214, 3.16933746,
       9.47962056, 4.59755548, 9.93780824, 8.50222742, 0.67033916,
       0.7680997 , 3.89928015, 5.10750796, 0.23213316, 7.22972843,
       5.45403522, 0.14627873, 2.31024876, 3.64709778, 4.94125794,
       8.9890525 , 4.96857027, 7.82692512, 3.82440752, 6.08652705,
       3.15458908, 6.77813816, 2.34337811, 2.47766461, 4.47326407,
       7.16964651, 5.03041095, 2.27432346, 2.58464947, 8.31960573,
       6.1079084 , 4.06609776, 9.62319325, 5.44977887, 9.72312348,
       3.35883305, 1.91267416, 1.78270747, 4.72766223, 4.33097185,
       8.65538898, 2.61953746, 4.05091517, 9.78499707, 1.64899334,
       2.74467793, 4.71359807, 8.08675696, 0.89846275, 4.35739942,
       3.7082654 , 4.31793983, 5.00649306, 8.50431795, 8.02075301,
       4.72356718, 2.33185499, 7.92272907, 8.60834256, 7.22456

In [14]:
np.random.uniform(0.0, 10.0, size=(3,3)) # 3x3 matrix populated w/ random floats between 0 and 10

array([[1.97134968, 9.8719721 , 3.25614689],
       [3.63576096, 7.91214218, 3.48837422],
       [9.66394753, 8.91367194, 3.30569732]])

### 1.4. Unequal chances

In [15]:
# easy but unpractical solution
chance = np.random.uniform(0.0, 100.0)

if chance <= 15:
    print("Turn left")
elif 15 < chance <= 95:
    print("Go straigt")
else:
    print("Turn right")

Go straigt


In [16]:
def direction():
    chance = np.random.uniform(0.0, 100.0)

    if chance <= 15:
        print("Turn left")
    elif 15 < chance <= 95:
        print("Go straigt")
    else:
        print("Turn right")

In [17]:
for i in range(10):
    direction()

Turn left
Go straigt
Go straigt
Go straigt
Go straigt
Go straigt
Go straigt
Turn left
Go straigt
Go straigt


In [18]:
# more practical solution
direction = [1,2,3]
probabilities = [0.15, 0.8, 0.05]
selected_direction = np.random.choice(direction, p=probabilities)

if selected_direction == 1:
    print("Turn left")
elif selected_direction == 2:
    print("Go straight")
else:
    print("Turn right")


Go straight


In [19]:
def direction2():
    direction = [1,2,3]
    probabilities = [0.15, 0.8, 0.05]
    selected_direction = np.random.choice(direction, p=probabilities)

    if selected_direction == 1:
        print("Turn left")
    elif selected_direction == 2:
        print("Go straight")
    else:
        print("Turn right")

In [20]:
for i in range(10):
    direction2()

Go straight
Go straight
Go straight
Go straight
Go straight
Turn left
Turn left
Turn left
Go straight
Go straight


### 1.5. Shuffling and permutation

In [21]:
cards_diamonds = [ str(i)+"_diamonds" for i in range(1,11)]
cards_spades = [str(i)+"_spades" for i in range(1,11)]
cards_hearts = [ str(i)+"_hearts" for i in range(1,11)]
cards_clubs = [ str(i)+"_clubs" for i in range(1,11)]

In [22]:
all_cards = np.concatenate([cards_diamonds, cards_spades, cards_hearts, cards_clubs]) 

In [23]:
print(all_cards)

['1_diamonds' '2_diamonds' '3_diamonds' '4_diamonds' '5_diamonds'
 '6_diamonds' '7_diamonds' '8_diamonds' '9_diamonds' '10_diamonds'
 '1_spades' '2_spades' '3_spades' '4_spades' '5_spades' '6_spades'
 '7_spades' '8_spades' '9_spades' '10_spades' '1_hearts' '2_hearts'
 '3_hearts' '4_hearts' '5_hearts' '6_hearts' '7_hearts' '8_hearts'
 '9_hearts' '10_hearts' '1_clubs' '2_clubs' '3_clubs' '4_clubs' '5_clubs'
 '6_clubs' '7_clubs' '8_clubs' '9_clubs' '10_clubs']


In [24]:
shuffled_cards = np.random.permutation(all_cards) # does not change the original array

In [25]:
shuffled_cards

array(['6_hearts', '10_hearts', '4_diamonds', '8_spades', '10_clubs',
       '9_clubs', '2_hearts', '2_spades', '7_hearts', '10_diamonds',
       '10_spades', '3_spades', '1_clubs', '8_clubs', '5_hearts',
       '4_spades', '1_hearts', '7_spades', '9_spades', '1_spades',
       '5_clubs', '3_clubs', '3_hearts', '2_clubs', '1_diamonds',
       '5_diamonds', '6_spades', '9_diamonds', '6_diamonds', '4_clubs',
       '8_diamonds', '2_diamonds', '7_diamonds', '9_hearts', '4_hearts',
       '3_diamonds', '5_spades', '7_clubs', '6_clubs', '8_hearts'],
      dtype='<U11')

In [26]:
np.random.shuffle(all_cards) # does change the original array

In [27]:
all_cards

array(['9_hearts', '5_clubs', '3_diamonds', '1_diamonds', '6_hearts',
       '8_hearts', '3_clubs', '1_clubs', '9_diamonds', '5_spades',
       '6_clubs', '2_diamonds', '10_diamonds', '2_hearts', '3_hearts',
       '1_spades', '10_clubs', '2_spades', '8_clubs', '4_hearts',
       '1_hearts', '7_clubs', '10_hearts', '6_diamonds', '10_spades',
       '8_spades', '9_clubs', '4_spades', '7_diamonds', '3_spades',
       '4_diamonds', '8_diamonds', '6_spades', '5_diamonds', '7_spades',
       '9_spades', '2_clubs', '4_clubs', '7_hearts', '5_hearts'],
      dtype='<U11')